authors:
  virtualguard101:
    name: ZHIGUO CAI
    description: Creator
    avatar: https://wiki.virtualguard101.com/assets/logo.png
    url: https://github.com/virtualguard101

  Butterblock233:
    name: Butter Block
    description: Friend
    avatar: https://www.gravatar.com/avatar/c696f1166a31429e0e2071f6098af4d4?s=240&d=mp
    url: https://github.com/Butterblock233
