## Page tree
nav:
  - index.md
  - Notebook: 
    - obsidian/index.md
    - 资源:
      - 学术资源: "obsidian/Misc/resources/学术资源.md"
      - 工程、求职、杂项资源: "obsidian/Misc/resources/工程、求职、杂项资源.md"
    - 工具:
      - Linux:
        - Linux杂项/基础: "obsidian/Tools/linux/Linux基础、杂项.md"
        - Linux定时任务: "obsidian/Tools/linux/Linux定时任务.md"
        - Shell Scripting: "obsidian/Tools/Shell Scripting.md"
        - Linux终端复用器: "obsidian/Tools/linux/tmux.md"
        - Timeshift: "obsidian/Tools/linux/Timeshift.md"
        - htop: "obsidian/Tools/linux/htop.md"
      - 远程服务器使用基础: "obsidian/Tools/远程服务器使用基础.md"
      - Git: "obsidian/Tools/Git.md"
      - Just: "obsidian/Tools/Just.md"
      - Astral uv: "obsidian/Tools/Astral uv.md"
      - Conda: "obsidian/Tools/Conda.md"
      - Jupyter Notebook: "obsidian/Tools/jupyter.ipynb"
      - 构建工具:
        - GNU Make: "obsidian/Tools/BuildTools/GNU Make.md"
        - CMake: "obsidian/Tools/BuildTools/CMake.md"
        - vcpkg: "obsidian/Tools/BuildTools/vcpkg.md"
        - SCons: "obsidian/Tools/BuildTools/SCons.md"
        - xmake: "obsidian/Tools/BuildTools/xmake.md"
    - 编程语言:
      - Python:
        - Python包管理: "obsidian/ProgrammingLanguage/python/Python包管理.md"
        - Python虚拟环境: "obsidian/ProgrammingLanguage/python/Python虚拟环境.md"
      - Golang:
        - Golang入门要点: "obsidian/ProgrammingLanguage/golang/Golang入门要点.md"
        - 基础:
          - 命名规范: "obsidian/ProgrammingLanguage/golang/Go命名规范.md"
          - Golang程序结构: "obsidian/ProgrammingLanguage/golang/Golang程序结构.md"
          - Golang函数: "obsidian/ProgrammingLanguage/golang/Golang函数.md"
          - Golang接口: "obsidian/ProgrammingLanguage/golang/Golang接口.md"
      - Rust:
        - Rust入门要点: "obsidian/ProgrammingLanguage/rust/Rust入门要点.md"
      - C++:
        - "Standard C++ Programming":
          - 基础类型与结构体: "obsidian/ProgrammingLanguage/cpp/cs106l/基础类型与结构体.md"
          - 初始化与引用操作: "obsidian/ProgrammingLanguage/cpp/cs106l/初始化与引用操作.md"
          - C++流: "obsidian/ProgrammingLanguage/cpp/cs106l/C++流.md"
          - STL容器: "obsidian/ProgrammingLanguage/cpp/cs106l/STL容器.md"
          - 迭代器和指针: "obsidian/ProgrammingLanguage/cpp/cs106l/迭代器和指针.md"
          - C++类 & 模板: "obsidian/ProgrammingLanguage/cpp/cs106l/C++类 & 模板.md"
          - Lambda表达式: "obsidian/ProgrammingLanguage/cpp/cs106l/Lambda表达式.md"
          - 运算符重载: "obsidian/ProgrammingLanguage/cpp/cs106l/运算符重载.md"
          - 特殊成员函数: "obsidian/ProgrammingLanguage/cpp/cs106l/特殊成员函数.md"
          - C++移动语义: "obsidian/ProgrammingLanguage/cpp/cs106l/C++移动语义.md"
          - C++类型安全、设计理念概述: "obsidian/ProgrammingLanguage/cpp/cs106l/C++类型安全、设计理念概述.md"
          - RAII & C++智能指针: "obsidian/ProgrammingLanguage/cpp/cs106l/RAII & C++智能指针.md"
      - JavaScript:
        - JavaScript入门要点: "obsidian/ProgrammingLanguage/javascript/JavaScript入门要点.md"
        - JS回调函数简单应用: "obsidian/ProgrammingLanguage/javascript/JS回调函数简单应用.md"
      - Java:
        - Java入门要点: "obsidian/ProgrammingLanguage/java/Java入门要点.md"
        - Java类与对象: "obsidian/ProgrammingLanguage/java/Java类与对象.md"
    - 数学:
      - 离散数学:
        - 集合 & 数学符号与逻辑命题: "obsidian/Math/DiscreteMath/集合 & 数学符号与逻辑命题.md"
        - 证明: "obsidian/Math/DiscreteMath/证明.md"
      - 线性代数:
        - 行列式: "obsidian/Math/LinearAlgebra/行列式.md"
        - 行列式的展开: "obsidian/Math/LinearAlgebra/行列式的展开.md"
        - 矩阵: "obsidian/Math/LinearAlgebra/矩阵.md"
        - 逆矩阵: "obsidian/Math/LinearAlgebra/逆矩阵.md"
        - 矩阵的行列式计算: "obsidian/Math/LinearAlgebra/矩阵的行列式计算.md"
        - 矩阵的初等变换: "obsidian/Math/LinearAlgebra/矩阵的初等变换.md"
        - 向量: "obsidian/Math/LinearAlgebra/向量.md"
        - 线性方程组: "obsidian/Math/LinearAlgebra/线性方程组.md"
        - 相似矩阵: "obsidian/Math/LinearAlgebra/相似矩阵.md"
        - 二次型: "obsidian/Math/LinearAlgebra/二次型.md"
    - 数据结构与算法:
      - 绪论:
      #   - 算法和算法评价: "obsidian/DataStructure/408/算法和算法评价.md"
        - 递归与迭代: "obsidian/DataStructure/408/迭代与递归.md"
      - 线性表:
        - 线性表的顺序表示: "obsidian/DataStructure/408/线性表的顺序表示.md"
        - 线性表的链式表示: "obsidian/DataStructure/408/线性表的链式表示.md"
      - 栈、队列与数组:
        - 栈: "obsidian/DataStructure/408/栈.md"
        - 队列: "obsidian/DataStructure/408/队列.md"
        - 栈与队列的应用: "obsidian/DataStructure/408/栈与队列的应用.md"
        - 数组和特殊矩阵: "obsidian/DataStructure/408/数组和特殊矩阵.md"
      - 串:
        - 串的定义和实现: "obsidian/DataStructure/408/串的定义和实现.md"
        - 串的模式匹配: "obsidian/DataStructure/408/串的模式匹配.md"
      - 树与二叉树:
        - 树与二叉树的基本概念: "obsidian/DataStructure/408/树与二叉树的基本概念.md"
        - 二叉树的遍历: "obsidian/DataStructure/408/二叉树的遍历.md"
        - 线索二叉树: "obsidian/DataStructure/408/线索二叉树.md"
        - 树与森林: "obsidian/DataStructure/408/树与森林.md"
        - 树与二叉树的应用: "obsidian/DataStructure/408/树与二叉树的应用.md"
      - 图:
        - 图的基本概念: "obsidian/DataStructure/408/图的基本概念.md"
        - 图的存储及基本操作: "obsidian/DataStructure/408/图的存储及基本操作.md"
        - 图的遍历: "obsidian/DataStructure/408/图的遍历.md"
        - 图的应用: "obsidian/DataStructure/408/图的应用.md"
    - 操作系统:
      - "408":
        - 操作系统概述:
          - 操作系统基本特性: "obsidian/OperatingSystem/408/操作系统基本特性.md"
          - 操作系统发展历程: "obsidian/OperatingSystem/408/操作系统发展历程.md"
          - 操作系统运行环境: "obsidian/OperatingSystem/408/操作系统运行环境.md"
        - 进程管理:
          - 进程的描述与控制: "obsidian/OperatingSystem/408/进程的描述与控制.md"
          - 处理机调度: "obsidian/OperatingSystem/408/处理机调度.md"
          - 同步与互斥: "obsidian/OperatingSystem/408/同步与互斥.md"
          - 死锁: "obsidian/OperatingSystem/408/死锁.md"
        - 内存管理:
          - 内存管理概述: "obsidian/OperatingSystem/408/内存管理概述.md"
          - 虚拟内存管理: "obsidian/OperatingSystem/408/虚拟内存管理.md"
        - 文件管理:
          - 文件系统概述: "obsidian/OperatingSystem/408/文件系统概述.md"
          - 目录: "obsidian/OperatingSystem/408/目录.md"
          - 文件系统: "obsidian/OperatingSystem/408/文件系统.md"
        - I/O管理:
          - 输入输出管理概述: "obsidian/OperatingSystem/408/输入输出管理概述.md"
          - 设备独立性缓存: "obsidian/OperatingSystem/408/设备独立性缓存.md"
          - 磁盘和固态硬盘: "obsidian/OperatingSystem/408/磁盘和固态硬盘.md"
      - 绪论:
        - 操作系统简易模型: "obsidian/OperatingSystem/intro/操作系统简易模型.md"
        - Introduction to Operating Systems: "obsidian/OperatingSystem/intro/Introduction to Operating Systems.md"
      - 虚拟化:
        - "The Abstraction: The Process": "obsidian/OperatingSystem/virtualization/The Abstraction - The Process.md"
        - "Process API": "obsidian/OperatingSystem/virtualization/Process API.md"
      - Linux环境下的进程创建与进程通信: "obsidian/OperatingSystem/Linux环境下的进程创建与进程通信.md"
    - 软件工程:
      - UML图: "obsidian/SoftwareEngineering/UML图.md"
    - 人工智能:
      - 机器学习:
        - "入门":
          - 监督学习与非监督学习: "obsidian/MachineLearning/coursera/监督学习与非监督学习.md"
          - 回归: 
            - 回归模型概述: "obsidian/MachineLearning/coursera/回归模型概述.md"
            - 模型表示法: "obsidian/MachineLearning/coursera/model-repr.ipynb"
            - 成本函数概述: "obsidian/MachineLearning/coursera/成本函数概述.md"
            - 成本函数可视化: "obsidian/MachineLearning/coursera/cost-func-visual.ipynb"
            - 梯度下降: "obsidian/MachineLearning/coursera/梯度下降.md"
            - 一元线性回归模型的梯度下降实现: "obsidian/MachineLearning/coursera/linear-grad-desent.ipynb"
            - 多元线性回归模型: "obsidian/MachineLearning/coursera/多元线性回归模型.md"
            - 特征缩放与特征工程: "obsidian/MachineLearning/coursera/feat-engineering.ipynb"
          - 分类:
            - 逻辑回归: "obsidian/MachineLearning/coursera/logistic-regression.ipynb"
            - 决策边界: "obsidian/MachineLearning/coursera/决策边界.md"
            - 逻辑损失与成本函数: "obsidian/MachineLearning/coursera/logistic-loss-cost.ipynb"
            - 逻辑回归的梯度下降: "obsidian/MachineLearning/coursera/logistic-grad-desent.ipynb"
          - 过拟合问题与正则化: "obsidian/MachineLearning/coursera/过拟合问题与正则化.md"
    - Web开发:
      - 入门基础:
        - HTML要点: "obsidian/Misc/HTML要点.md"
        - CSS要点: "obsidian/Misc/CSS要点.md"
    - Misc:
      - 科学上网:
        - 透明代理: "obsidian/Misc/ScientificInternetAccess/透明代理.md"
      - 正则表达式: "obsidian/Misc/正则表达式.md"
      - 开源协议: "obsidian/Misc/开源协议.md"
      - 使用SSH访问GitHub远程仓库: "obsidian/Misc/使用SSH访问GitHub远程仓库.md"
         
  - Blog:
    - blog/index.md
  - Projects:
    - Showcase: projects/index.md
    - "ForyoClassifierCNN: A music classification project based on PyTorch": projects/ForyoClassifierCNN.md
    - "MkDocs-Note: 一个用于在MkDocs文档中管理并部署笔记的插件": projects/MkDocs-Note.md
    - "3BodySimulator: Python & C++ 项目标准化构建": projects/3BodySimulator.md
    - "SpaceCaculator: Python3面向对象简单应用": projects/SpaceCaculator.md
  - Credits: credits.md
  # - Todo: todo.md

not_in_nav: |
  projects/log/
